INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('乃木坂46','のぎざかふぉーてぃしっくす','https://nogizaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('日向坂46','ひなたざかふぉーてぃしっくす','https://hinatazaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('櫻坂46','さくらざかふぉーてぃしっくす','https://sakurazaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('ももいろクローバーZ','ももいろくろーばーぜっと','https://www.momocho.net');

INSERT INTO MEMBERS(MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY,MEMBER_PHOTO,ARTIST_ID) VALUES
('五百城茉央','いおきまお','2005-07-29', '',1),
('あいうえお','あいうえお','2002-07-21', '',1),
('かきくけこ','かきくけこ','2004-03-26', '',1);